### ISSUE TITLE
Installation works, however, starting errors

### ISSUE THREAD

**Issue by alemstrom** [wimactel/FreeSwitch-DataDog-Metrics#1]
root@fusionpbx-dev:~/FreeSwitch-DataDog-Metrics-master# python --version
Python 2.7.16
root@fusionpbx-dev:~/FreeSwitch-DataDog-Metrics-master# /etc/init.d/fsmetrics start
Starting server
Traceback (most recent call last):
  File "/usr/share/python-daemon/fsmetrics.py", line 9, in <module>
    from daemon import runner
ImportError: No module named daemon

Trying to install here, however, receiving this notice.

**Comment by alemstrom** [comment]
Apparently python-daemon package on debian didn't install.  It's installed now but I'm receiving:

Traceback (most recent call last):
  File "/usr/share/python-daemon/fsmetrics.py", line 159, in <module>
    daemon_runner = runner.DaemonRunner(app)
  File "/usr/local/lib/python2.7/dist-packages/daemon/runner.py", line 119, in __init__
    app.pidfile_path, app.pidfile_timeout)
  File "/usr/local/lib/python2.7/dist-packages/daemon/runner.py", line 304, in make_pidlockfile
    lockfile = pidfile.TimeoutPIDLockFile(path, acquire_timeout)
  File "/usr/local/lib/python2.7/dist-packages/daemon/pidfile.py", line 40, in __init__
    super().__init__(path, *args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)
